# Generated by Django 4.0.5 on 2022-06-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
