# Generated by Django 4.0.5 on 2022-06-22 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('time_purchase', models.DateTimeField(auto_now_add=True)),
                ('price_at_time_purchase', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-time_purchase'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['username'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_request_return', models.DateTimeField(auto_now_add=True)),
                ('to_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_shop.purchase')),
            ],
            options={
                'verbose_name': 'Purchase returns',
                'verbose_name_plural': 'Purchase returns',
                'ordering': ['-time_request_return'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_shop.product'),
        ),
    ]
